version: '2'
services:
  cw2015-battery:
    build:
      context: ./
      dockerfile: Dockerfile

    labels:
      - 'io.balena.image.class=overlay'
      - 'io.balena.image.requires-reboot=1'
      - 'io.balena.image.store=data'
